# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        flake8 --count --show-source --statistics bot/ src/ tests/
    - name: Type check with mypy
      run: |
        mypy --install-types --non-interactive bot/ src/ tests/
    - name: Security check with bandit
      run: |
        bandit --recursive bot/ src/ tests/
    - name: Test with pytest and report coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        if [ -f bot/requirements.txt ]; then pip install -r bot/requirements.txt; fi
        pytest --cov-report=xml:coverage.xml --cov=src --cov=bot tests/
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
